name: Deploy images

on:
  workflow_dispatch:

jobs:
  py-27:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Build image ğŸ—
        run: |
          cd docker/law-py27
          docker build . -t riga/law:py27 -t riga/law:py2

      - name: Deploy image ğŸ³
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: riga/law
          tags: "py27,py2"
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
